# Repositories module — re-exports all database CRUD functions
from repositories.postgres_repo import (
    init_db,
    close_pool,
    get_pool,
    create_user,
    get_user_by_email,
    get_user_by_id,
    create_conversation,
    append_message,
    create_debate_session,
    get_debate_session_by_conversation_id,
    get_user_history,
    update_conversation_timestamp,
    rename_conversation,
    delete_conversation,
    clear_all_history,
    get_conversation_with_messages,
    log_chunk_retrieval,
    log_detected_mistakes,
    get_pdf_quality_scores,
)
from repositories.qdrant_repo import (
    get_embedding,
    get_qdrant_client,
    init_qdrant_collections,
    upsert_pdf_summary,
    get_user_pdf_summaries,
    upsert_pdf_chunks,
    search_chunks,
    search_pdf_summary,
    search_chunks_by_pdf_id,
    get_pdf_ids_by_names,
    get_most_recent_pdf_id,
)
